import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:rest_countries/utils/sizes.dart';

class SplashScreen extends StatefulWidget {
  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  List<String> flags = [
    '🇦🇫',
    '🇦🇱',
    '🇩🇿',
    '🇦🇸',
    '🇦🇩',
    '🇦🇴',
    '🇦🇮',
    '🇦🇶',
    '🇦🇬',
    '🇦🇷',
    '🇦🇲',
    '🇦🇺',
    '🇦🇹',
    '🇦🇿',
    '🇧🇸',
    '🇧🇭',
    '🇧🇩',
    '🇧🇧',
    '🇧🇾',
    '🇧🇪',
    '🇧🇿',
    '🇧🇯',
    '🇧🇹',
    '🇧🇴',
    '🇧🇦',
    '🇧🇼',
    '🇧🇷',
    '🇧🇳',
    '🇧🇬',
    '🇧🇫',
    '🇧🇮',
    '🇨🇻',
    '🇰🇭',
    '🇨🇲',
    '🇨🇦',
    '🇨🇫',
    '🇹🇩',
    '🇨🇱',
    '🇨🇳',
    '🇨🇴',
    '🇰🇲',
    '🇨🇩',
    '🇨🇬',
    '🇨🇷',
    '🇨🇮',
    '🇭🇷',
    '🇨🇺',
    '🇨🇾',
    '🇨🇿',
    '🇩🇰',
    '🇩🇯',
    '🇩🇲',
    '🇩🇴',
    '🇪🇨',
    '🇪🇬',
    '🇸🇻',
    '🇬🇶',
    '🇪🇷',
    '🇪🇪',
    '🇪🇹',
    '🇫🇯',
    '🇫🇮',
    '🇫🇷',
    '🇬🇦',
    '🇬🇲',
    '🇬🇪',
    '🇩🇪',
    '🇬🇭',
    '🇬🇷',
    '🇬🇩',
    '🇬🇹',
    '🇬🇳',
    '🇬🇼',
    '🇬🇾',
    '🇭🇹',
    '🇭🇳',
    '🇭🇺',
    '🇮🇸',
    '🇮🇳',
    '🇮🇩',
    '🇮🇷',
    '🇮🇶',
    '🇮🇪',
    '🇮🇱',
    '🇮🇹',
    '🇯🇲',
    '🇯🇵',
    '🇯🇴',
    '🇰🇿',
    '🇰🇪',
    '🇰🇮',
    '🇰🇵',
    '🇰🇷',
    '🇽🇰',
    '🇰🇼',
    '🇰🇬',
    '🇱🇦',
    '🇱🇻',
    '🇱🇧',
    '🇱🇸',
    '🇱🇷',
    '🇱🇾',
    '🇱🇹',
    '🇱🇺',
    '🇲🇰',
    '🇲🇬',
    '🇲🇼',
    '🇲🇾',
    '🇲🇻',
    '🇲🇱',
    '🇲🇹',
    '🇲🇭',
    '🇲🇷',
    '🇲🇺',
    '🇲🇽',
    '🇫🇲',
    '🇲🇩',
    '🇲🇨',
    '🇲🇳',
    '🇲🇪',
    '🇲🇦',
    '🇲🇿',
    '🇲🇲',
    '🇳🇦',
    '🇳🇷',
    '🇳🇵',
    '🇳🇱',
    '🇳🇿',
    '🇳🇮',
    '🇳🇪',
    '🇳🇬',
    '🇳🇺',
    '🇳🇴',
    '🇴🇲',
    '🇵🇰',
    '🇵🇼',
    '🇵🇸',
    '🇵🇦',
    '🇵🇬',
    '🇵🇾',
    '🇵🇪',
    '🇵🇭',
    '🇵🇱',
    '🇵🇹',
    '🇶🇦',
    '🇷🇴',
    '🇷🇺',
    '🇷🇼',
    '🇰🇳',
    '🇱🇨',
    '🇻🇨',
    '🇼🇸',
    '🇸🇲',
    '🇸🇹',
    '🇸🇦',
    '🇸🇳',
    '🇷🇸',
    '🇸🇨',
    '🇸🇱',
    '🇸🇬',
    '🇸🇰',
    '🇸🇮',
    '🇸🇧',
    '🇸🇴',
    '🇿🇦',
    '🇸🇸',
    '🇪🇸',
    '🇱🇰',
    '🇸🇩',
    '🇸🇷',
    '🇸🇪',
    '🇨🇭',
    '🇸🇾',
    '🇹🇼',
    '🇹🇯',
    '🇹🇿',
    '🇹🇭',
    '🇹🇱',
    '🇹🇬',
    '🇹🇴',
    '🇹🇹',
    '🇹🇳',
    '🇹🇷',
    '🇹🇲',
    '🇹🇻',
    '🇺🇬',
    '🇺🇦',
    '🇦🇪',
    '🇬🇧',
    '🇺🇸',
    '🇺🇾',
    '🇺🇿',
    '🇻🇺',
    '🇻🇦',
    '🇻🇪',
    '🇻🇳',
    '🇾🇪',
    '🇿🇲',
    '🇿🇼'
  ];

  bool isMovedFlag1 = false;

  void makeAllTrue() {
    setState(() {
      isMovedFlag1 = true;
    });
  }

  @override
  void initState() {
    super.initState();

    Future.delayed(const Duration(seconds: 1), () {
      return makeAllTrue();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
      children: [
        AnimatedPositioned(
          top: isMovedFlag1 ? SizeUtil.screenFullHeight(context) / 2 : 0,
          left: isMovedFlag1 ? SizeUtil.screenWidth(context) / 4 : 0,
          duration: const Duration(seconds: 1),
          child: Text(
            flags[0],
            style: TextStyle(
              fontSize: 30.sp,
            ),
          ),
        ),
        AnimatedPositioned(
          top: isMovedFlag1 ? SizeUtil.screenFullHeight(context) / 2 : 0,
          left: isMovedFlag1 ? (SizeUtil.screenWidth(context) / 4) * 2 : 0,
          duration: const Duration(seconds: 1),
          child: Text(
            flags[2],
            style: TextStyle(
              fontSize: 30.sp,
            ),
          ),
        ),
        AnimatedPositioned(
          top: isMovedFlag1 ? SizeUtil.screenFullHeight(context) / 2 : 0,
          left: isMovedFlag1 ? (SizeUtil.screenWidth(context) / 4) * 3 : 0,
          duration: const Duration(seconds: 1),
          child: Text(
            flags[3],
            style: TextStyle(
              fontSize: 30.sp,
            ),
          ),
        ),
        AnimatedPositioned(
          top: isMovedFlag1 ? 70.h : 0,
          left: isMovedFlag1 ? 200.w : 0,
          duration: const Duration(seconds: 1),
          child: Text(
            flags[4],
            style: TextStyle(
              fontSize: 30.sp,
            ),
          ),
        )
      ],
    ));
  }
}
